### ISSUE TITLE
How do you solve the NoSuchMethodError UIObject.getElement()Lcom/google/gwt/user/client/Element;

### ISSUE THREAD

**Issue by skarzhevskyy** [Doctusoft/gwt-mock-2.5.1#1]
Interesting project!
I tried to run my code with gwt-mock-2.5.1 and there are some binary incompatibility problems in my code.

NoSuchMethodError UIObject.getElement()Lcom/google/gwt/user/client/Element;
Happens because or UIObject signature was changed in gwt-mock.

How do you deal with this in your tests? When your codes java is complied with actual java and tests run again different binary?

**Comment by gabor-farkas** [comment]
Yup, I had to remove `com.google.gwt.user.client.Element` completely and change all usages to `com.google.gwt.dom.client.Element`. So if your code also refers user.client.Element, you have to change it for dom.client.Element. Things will compile and work just the same.

**Comment by skarzhevskyy** [comment]
I managed to run my code while compiling my project againt mock to see if
it works.

The places where Element is used i delegated to special adapter that is
compiled in two versions.

But this is problem for my multi module setup where jar complied against
standard gwt and some 3rd party libraries.

Everywhere where inheritance is used to create widget the tests will fail
while adding this widget to parent.

I will consider changing code that I want to test to use composition. But
this does not look like a final solution.

BTW My project is based on GWT 2.8 so far I have not found a showstopper .

I will try to find other solutions for binary incompatibility...

Yup, I had to remove com.google.gwt.user.client.Element completely and
change all usages to com.google.gwt.dom.client.Element. So if your code
also refers user.client.Element, you have to change it for
dom.client.Element. Things will compile and work just the same.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Doctusoft/gwt-mock-2.5.1/issues/1#issuecomment-222084162,
or mute the thread
https://github.com/notifications/unsubscribe/AGpA8TGZIYgtyMA70itOZUI5TvheIzNEks5qFqPUgaJpZM4IoA60
.

**Comment by gabor-farkas** [comment]
Ahh yes, I get the point I think.

Although our gwt project is in a single maven module, I also created a separate maven module for the gwt-mock tests. To avoid class incompatibility, I refer the main maven module not as a dependency, but as external source from the test project.
It's done by:

``` xml
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.7</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>
                                    ../{{main module}}/src/main/java
                                </source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

I think this would work for you too

**Comment by skarzhevskyy** [comment]
I have a better idea  that will also resolves the binary compatibility with third party libraries.

Please review:
https://github.com/Doctusoft/gwt-mock-2.5.1/pull/3

**Comment by skarzhevskyy** [comment]
Update. I resolve my problem
1. create a fresh test projects https://github.com/skarzhevskyy/gwt-mock-2.5.1/tree/app-tests
    If works fine, no binary compatibility problems
2. Than I found in my widgets an interface 

```
interface MyInterface {
   ....
   Element getElement();
   ....
}
```

Than was causing all the problems . Removing this function from interface and delegating all .getElement() to single Adapter solved my problems.  

This is what I added to my application to enable running it in gwt-mock

```
import com.google.gwt.dom.client.Element;
import com.google.gwt.user.client.ui.IsWidget;
import com.google.gwt.user.client.ui.Widget;

/**
 * Java binary code compatibility adapter for GWT Mock.
 * There is copy class compiled again GWT Mock in module my-gwt-mock-tests to be used first in class path during tests.
 */
public final class GwtMockAdapter {

    public final static Element getElement(Widget widget) {
        return widget.getElement();
    }

    public final static Element getElement(IsWidget widget) {
        return widget.asWidget().getElement();
    }

}
```

**Comment by gabor-farkas** [comment]
looks cool
