### ISSUE TITLE
Need new Mock management class in Mock Library

### ISSUE THREAD

**Issue by skarzhevskyy** [Doctusoft/gwt-mock-2.5.1#5]
The class should be an entry point for unit tests to configure the Mock library.

Possible names  BrowserMock or GWTMockBridge

Functions that will be there.
-  GWT.addCustomSupplier
-  GWT.registerImplementation(Class,Class)  (simplified version of above)
- reset()  or tearDown() //  Remove all initialization doe in Mock to be able to start new test.
  will call
         RootPanel.get().clear();
        com.doctusoft.gwtmock.Document.reset();
  In future some other methods to clear up  static references i Mock implementation.

**Comment by gabor-farkas** [comment]
Yup, sounds fine. I'd use just GWTMock, what do you think?

**Comment by skarzhevskyy** [comment]
OK name is selected.

I will create a proposal next week for you to review.

**Comment by skarzhevskyy** [comment]
Proposal added to existing PR #4 
[Cleaner way to interact with the Mock library.](https://github.com/Doctusoft/gwt-mock-2.5.1/pull/4/commits/d4824fb313ca0ab0b814450b3d7f7ee8290270c4)
